import { Member, Team, Session, Equipment, Transaction, AssociationInfo, AdministrativeDocument } from "./types";

export const INITIAL_MEMBERS: Member[] = [
  {
    id: "m-1",
    name: "Jean Dupont",
    age: 24,
    email: "jean.dupont@example.com",
    phone: "06 12 34 56 78",
    createdAt: "2026-05-10T10:00:00.000Z",
    licenseNumber: "FFF-2026-8491",
    gender: "M",
    category: "Sénior",
    role: "Joueur / Capitaine",
    address: "14 Rue des Lilas",
    city: "Paris",
    postalCode: "75011",
    medicalCertificateStatus: "valid",
    medicalCertificateDate: "2026-01-15",
    emergencyContactName: "Sophie Dupont",
    emergencyContactPhone: "06 12 34 56 99",
    emergencyContactRelation: "Épouse",
    paymentStatus: "paid",
    paymentAmount: 180,
    paymentMethod: "Carte CB",
    selectedTeamIds: ["t-1"]
  },
  {
    id: "m-2",
    name: "Marie Curie",
    age: 28,
    email: "marie.curie@example.com",
    phone: "07 98 76 54 32",
    createdAt: "2026-05-12T11:30:00.000Z",
    licenseNumber: "FFB-2026-1029",
    gender: "F",
    category: "Sénior",
    role: "Capitaine Féminines",
    address: "8 Avenue de la Science",
    city: "Paris",
    postalCode: "75005",
    medicalCertificateStatus: "valid",
    medicalCertificateDate: "2026-02-10",
    emergencyContactName: "Pierre Curie",
    emergencyContactPhone: "07 98 76 54 00",
    emergencyContactRelation: "Époux",
    paymentStatus: "paid",
    paymentAmount: 180,
    paymentMethod: "Virement",
    selectedTeamIds: ["t-2"]
  },
  {
    id: "m-3",
    name: "Thomas Dubois",
    age: 19,
    email: "thomas.dubois@example.com",
    phone: "06 55 44 33 22",
    createdAt: "2026-05-15T14:20:00.000Z",
    licenseNumber: "FFF-2026-3392",
    gender: "M",
    category: "U20 / Espoir",
    role: "Joueur",
    address: "42 Rue Pasteur",
    city: "Boulogne-Billancourt",
    postalCode: "92100",
    medicalCertificateStatus: "pending",
    medicalCertificateDate: "2025-09-01",
    emergencyContactName: "Marc Dubois",
    emergencyContactPhone: "06 55 44 00 11",
    emergencyContactRelation: "Père",
    paymentStatus: "paid",
    paymentAmount: 150,
    paymentMethod: "Espèces",
    selectedTeamIds: ["t-1"]
  },
  {
    id: "m-4",
    name: "Sophie Laurent",
    age: 31,
    email: "sophie.laurent@example.com",
    phone: "06 11 22 33 44",
    createdAt: "2026-05-18T09:15:00.000Z",
    licenseNumber: "FFB-2026-7821",
    gender: "F",
    category: "Sénior",
    role: "Meneuse de jeu",
    address: "5 Place de la République",
    city: "Montreuil",
    postalCode: "93100",
    medicalCertificateStatus: "valid",
    medicalCertificateDate: "2026-03-01",
    emergencyContactName: "Claire Laurent",
    emergencyContactPhone: "06 11 22 99 88",
    emergencyContactRelation: "Sœur",
    paymentStatus: "paid",
    paymentAmount: 180,
    paymentMethod: "Virement",
    selectedTeamIds: ["t-2"]
  },
  {
    id: "m-5",
    name: "Lucas Bernard",
    age: 22,
    email: "lucas.bernard@example.com",
    phone: "07 44 55 66 77",
    createdAt: "2026-05-20T16:45:00.000Z",
    licenseNumber: "FFF-2026-9042",
    gender: "M",
    category: "Sénior",
    role: "Défenseur",
    address: "19 Rue de la Paix",
    city: "Versailles",
    postalCode: "78000",
    medicalCertificateStatus: "valid",
    medicalCertificateDate: "2026-01-20",
    emergencyContactName: "Hélène Bernard",
    emergencyContactPhone: "07 44 55 00 22",
    emergencyContactRelation: "Mère",
    paymentStatus: "paid",
    paymentAmount: 180,
    paymentMethod: "Carte CB",
    selectedTeamIds: ["t-1"]
  },
  {
    id: "m-6",
    name: "Amélie Martin",
    age: 25,
    email: "amelie.martin@example.com",
    phone: "06 88 99 00 11",
    createdAt: "2026-05-22T10:10:00.000Z",
    licenseNumber: "FFB-2026-4410",
    gender: "F",
    category: "Sénior",
    role: "Ailière",
    address: "3 Boulevard Haussmann",
    city: "Paris",
    postalCode: "75009",
    medicalCertificateStatus: "pending",
    medicalCertificateDate: "2025-10-15",
    emergencyContactName: "Julien Martin",
    emergencyContactPhone: "06 88 99 55 44",
    emergencyContactRelation: "Frère",
    paymentStatus: "pending",
    paymentAmount: 180,
    paymentMethod: "Chèque",
    selectedTeamIds: ["t-2"]
  }
];

export const INITIAL_TEAMS: Team[] = [
  {
    id: "t-1",
    name: "Séniors Masculins A",
    coach: "Philippe Garcia",
    assistantCoach: "Antoine Roux",
    memberIds: ["m-1", "m-3", "m-5"],
    createdAt: "2026-05-25T12:00:00.000Z",
    category: "Sénior",
    genderCategory: "Masculin",
    sport: "Football",
    division: "Régionale 1",
    trainingSchedule: "Mardi & Enjeudi • 19h00 - 20h45",
    homeGround: "Stade Municipal - Terrain Synthétique A",
    maxMembers: 18,
    captainId: "m-1",
    teamColor: "#4f46e5",
    description: "Équipe fanion compétition engagée en championnat régional."
  },
  {
    id: "t-2",
    name: "Féminines Elite",
    coach: "Nathalie Simon",
    assistantCoach: "Claire Moreau",
    memberIds: ["m-2", "m-4", "m-6"],
    createdAt: "2026-05-26T14:00:00.000Z",
    category: "Sénior",
    genderCategory: "Féminin",
    sport: "Basketball",
    division: "Nationale 3",
    trainingSchedule: "Lundi & Mercredi • 18h30 - 20h15",
    homeGround: "Gymnase Pasteur - Salle Couverte",
    maxMembers: 15,
    captainId: "m-2",
    teamColor: "#ec4899",
    description: "Équipe première féminine axée sur la haute performance et la formation."
  }
];

export const INITIAL_SESSIONS: Session[] = [
  {
    id: "s-1",
    title: "Entraînement Tactique & Placement",
    type: "Entraînement",
    date: "2026-07-20",
    time: "18:30",
    durationMinutes: 90,
    teamId: "t-1",
    location: "Stade Municipal - Terrain Synthétique A",
    intensity: "Modérée",
    equipment: ["Chasubles rouges & bleues", "Plots & cônes", "Ballons de match"],
    notes: "Présence obligatoire 15min avant le début. Prévoir tenue d'entraînement complète."
  },
  {
    id: "s-2",
    title: "Préparation Physique & Cardio",
    type: "Entraînement",
    date: "2026-07-21",
    time: "19:00",
    durationMinutes: 75,
    teamId: "t-2",
    location: "Salle de Musculation - Complexe Pasteur",
    intensity: "Élevée",
    equipment: ["Tapis de sol", "Échelles de rythme", "Chronomètre"],
    notes: "Travail de VMA et de renforcement musculaire du bas du corps."
  },
  {
    id: "s-3",
    title: "Match Amical vs FC Métropole",
    type: "Match",
    date: "2026-07-23",
    time: "20:00",
    durationMinutes: 120,
    teamId: "t-1",
    location: "Complexe Sportif Municipal",
    opponent: "FC Métropole",
    homeAway: "Domicile",
    intensity: "Élevée",
    equipment: ["Tenue de match officielle", "Trousse de secours", "Feuille de match"],
    notes: "Rendez-vous à 19h00 aux vestiaires pour la causerie d'avant-match."
  },
  {
    id: "s-4",
    title: "Séance d'Endurance & Vitesse",
    type: "Entraînement",
    date: "2026-07-20",
    time: "17:00",
    durationMinutes: 60,
    teamId: "t-2",
    location: "Piste d'Athlétisme",
    intensity: "Élevée",
    equipment: ["Sifflet", "Chronomètres"],
    notes: "Hydratation fréquente durant la séance."
  },
  {
    id: "s-5",
    title: "Coordination, Tirs & Débriefing",
    type: "Entraînement",
    date: "2026-07-24",
    time: "10:30",
    teamId: "t-2",
    location: "Gymnase Central"
  }
];

export const INITIAL_EQUIPMENT: Equipment[] = [
  {
    id: "e-1",
    name: "Ballons Match Taille 5",
    category: "Ballons",
    quantity: 15,
    condition: "Bon état",
    assignedToType: "team",
    assignedToId: "t-1",
    location: "Local Matériel A - Étagère 1",
    notes: "Ballons homologués compétition",
    createdAt: "2026-06-01T09:00:00.000Z"
  },
  {
    id: "e-2",
    name: "Jeux de Maillots Bleus (Séniors)",
    category: "Textile",
    quantity: 18,
    condition: "Neuf",
    assignedToType: "team",
    assignedToId: "t-1",
    location: "Vestiaire Principale - Armoire 3",
    notes: "Flocage sponsor 2026",
    createdAt: "2026-06-05T14:30:00.000Z"
  },
  {
    id: "e-3",
    name: "Plots & Cône d'Entraînement",
    category: "Matériel",
    quantity: 60,
    condition: "Bon état",
    assignedToType: "none",
    location: "Local Matériel B",
    notes: "Lot de 30 rouges et 30 jaunes",
    createdAt: "2026-06-10T11:15:00.000Z"
  },
  {
    id: "e-4",
    name: "Trousse de Soins Complète",
    category: "Médical",
    quantity: 4,
    condition: "Bon état",
    assignedToType: "team",
    assignedToId: "t-2",
    location: "Infirmerie / Sac du coach",
    notes: "Poches de glace et bandes élastiques rechargées",
    createdAt: "2026-06-12T16:00:00.000Z"
  },
  {
    id: "e-5",
    name: "Cages de But Amovibles",
    category: "Infrastructure",
    quantity: 2,
    condition: "À réparer",
    assignedToType: "none",
    location: "Terrain Synthétique",
    notes: "Filet déchiré sur le but de droite",
    createdAt: "2026-06-15T08:45:00.000Z"
  },
  {
    id: "e-6",
    name: "Chasubles Jaune Fluo",
    category: "Textile",
    quantity: 30,
    condition: "Usé",
    assignedToType: "none",
    location: "Local Matériel A",
    notes: "Tissu distendu, nécessite réparation/couture",
    createdAt: "2026-06-18T10:20:00.000Z"
  },
  {
    id: "e-7",
    name: "Manomètres & Pompes Vétustes",
    category: "Matériel",
    quantity: 3,
    condition: "À remplacer",
    assignedToType: "none",
    location: "Atelier Entretien",
    notes: "Joints défectueux et embouts cassés. À remplacer urgemment.",
    createdAt: "2026-06-20T11:00:00.000Z"
  },
  {
    id: "e-8",
    name: "Table de Marque Électronique",
    category: "Infrastructure",
    quantity: 1,
    condition: "Hors service",
    assignedToType: "team",
    assignedToId: "t-1",
    location: "Gymnase Central",
    notes: "Affichage LED défaillant. Remplacement à prévoir.",
    createdAt: "2026-06-22T15:10:00.000Z"
  }
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: "tx-1",
    title: "Subvention Municipale Annuelle 2026",
    type: "income",
    category: "Subventions",
    amount: 3500,
    date: "2026-01-15",
    paymentMethod: "Virement",
    status: "Payé",
    notes: "Attribuée par la Mairie pour le pôle jeunesse",
    createdAt: "2026-01-15T10:00:00.000Z"
  },
  {
    id: "tx-2",
    title: "Cotisation Annuelle - Thomas Dupont",
    type: "income",
    category: "Cotisations",
    amount: 180,
    date: "2026-02-01",
    paymentMethod: "Carte CB",
    status: "Payé",
    memberId: "m-1",
    notes: "Licence compétition + maillot inclus",
    createdAt: "2026-02-01T14:20:00.000Z"
  },
  {
    id: "tx-3",
    title: "Achat de 18 Maillots Bleus Séniors",
    type: "expense",
    category: "Équipements & Matériel",
    amount: 640,
    date: "2026-02-10",
    paymentMethod: "Virement",
    status: "Payé",
    notes: "Facture EquipSport N°84920",
    createdAt: "2026-02-10T11:15:00.000Z"
  },
  {
    id: "tx-4",
    title: "Sponsor Maillot - Boulangerie Moderne",
    type: "income",
    category: "Sponsor & Partenariat",
    amount: 800,
    date: "2026-03-05",
    paymentMethod: "Chèque",
    status: "Payé",
    notes: "Contrat de partenariat saison 2026",
    createdAt: "2026-03-05T16:00:00.000Z"
  },
  {
    id: "tx-5",
    title: "Recettes Buvette Tournoi de Printemps",
    type: "income",
    category: "Événements & Buvette",
    amount: 420.50,
    date: "2026-04-12",
    paymentMethod: "Espèces",
    status: "Payé",
    notes: "Encaissement espèces fin de week-end",
    createdAt: "2026-04-12T18:30:00.000Z"
  },
  {
    id: "tx-6",
    title: "Location Créneau Gymnase Annexe",
    type: "expense",
    category: "Infrastructures & Salles",
    amount: 250,
    date: "2026-05-02",
    paymentMethod: "Prélèvement",
    status: "Payé",
    notes: "Forfait mensuel créneaux supplémentaires",
    createdAt: "2026-05-02T09:00:00.000Z"
  },
  {
    id: "tx-7",
    title: "Cotisation Annuelle - Sophie Martin",
    type: "income",
    category: "Cotisations",
    amount: 180,
    date: "2026-06-01",
    paymentMethod: "Virement",
    status: "En attente",
    memberId: "m-2",
    notes: "Relance envoyée par email",
    createdAt: "2026-06-01T08:00:00.000Z"
  },
  {
    id: "tx-8",
    title: "Achat Matériel Médical & Poches de Glace",
    type: "expense",
    category: "Équipements & Matériel",
    amount: 115.80,
    date: "2026-06-10",
    paymentMethod: "Carte CB",
    status: "Payé",
    notes: "Pharmacie du Centre",
    createdAt: "2026-06-10T15:45:00.000Z"
  }
];

export const INITIAL_ASSOCIATION_INFO: AssociationInfo = {
  name: "Club Omnisports de la Vallée",
  slogan: "Passion, Esprit d'équipe & Dépassement de soi",
  siret: "123 456 789 00012",
  rna: "W751029384",
  apeCode: "9312Z - Clubs de sport",
  creationDate: "2012-04-15",
  address: "12 Avenue des Sports, 75000 Paris",
  email: "contact@omnisports-vallee.fr",
  phone: "01 42 68 00 00",
  season: "2025 - 2026",
  currency: "EUR (€)",
  autoReminders: true,
  presidentName: "Marie DUBOIS",
  treasurerName: "Jean-Pierre MARTIN",
  secretaryName: "Claire MOREAU",
  signatoryName: "Marie DUBOIS - Présidente",
  federationName: "Fédération Française de Handball (FFHB)",
  federationNumber: "5875042",
  sportsAgreementNumber: "APS-75-2014-88",
  insuranceCompany: "MAIF Associations & Collectivités",
  insurancePolicyNumber: "4820193-H",
  bankName: "Crédit Mutuel",
  bankAccountHolder: "Club Omnisports de la Vallée",
  iban: "FR76 1027 8021 5400 0123 4567 889",
  bic: "CMUTFR2PP",
  website: "https://www.omnisports-vallee.fr"
};

export const INITIAL_DOCUMENTS: AdministrativeDocument[] = [
  {
    id: "doc-1",
    title: "Statuts Officiels de l'Association (Version déposée en Préfecture)",
    type: "Statuts & Règlements",
    category: "Juridique & Gouvernance",
    referenceNumber: "STAT-2012-V3",
    issueDate: "2012-04-15",
    description: "Statuts constitutifs de l'association loi 1901 approuvés en Assemblée Générale Constitutive et déclarés en Préfecture de Police.",
    fileName: "Statuts_Club_Omnisports_2012_Signes.pdf",
    fileSize: "1.8 Mo",
    fileType: "pdf",
    isConfidential: false,
    signatories: ["Marie DUBOIS (Présidente)", "Jean-Pierre MARTIN (Trésorier)", "Claire MOREAU (Secrétaire)"],
    status: "valid",
    tags: ["Statuts", "Préfecture", "Loi 1901", "Gouvernance"],
    season: "Toutes saisons",
    locationStored: "Bureau Administratif - Armoire 1 - Classeur Rouge",
    createdAt: "2026-01-10T09:00:00.000Z",
    notes: "Dépôt légal validé le 15/04/2012 au Journal Officiel des Associations."
  },
  {
    id: "doc-2",
    title: "Règlement Intérieur du Club (Saison 2025-2026)",
    type: "Statuts & Règlements",
    category: "Juridique & Gouvernance",
    referenceNumber: "RI-2025-2026",
    issueDate: "2025-09-01",
    validUntilDate: "2026-08-31",
    description: "Règles de vie du club, chartes des joueurs, entraîneurs et parents, sanctions et modalités d'utilisation des équipements.",
    fileName: "Reglement_Interieur_2025_2026.pdf",
    fileSize: "850 Ko",
    fileType: "pdf",
    isConfidential: false,
    signatories: ["Marie DUBOIS (Présidente)", "Claire MOREAU (Secrétaire)"],
    status: "valid",
    tags: ["Règlement", "Charte", "Adhérents", "Saison 2025-2026"],
    season: "2025 - 2026",
    locationStored: "Bureau Administratif - Classeur Accueil",
    createdAt: "2026-01-12T10:30:00.000Z"
  },
  {
    id: "doc-3",
    title: "Procès-Verbal de l'Assemblée Générale Ordinaire 2025",
    type: "Procès-Verbaux (PV d'AG & CA)",
    category: "Assemblées & Décisions",
    referenceNumber: "PV-AG-2025-06",
    issueDate: "2025-06-28",
    description: "PV constatant l'approbation du rapport moral, du bilan financier, du quitus au trésorier et renouvellement du bureau.",
    fileName: "PV_Assemblee_Generale_Ordinaire_2025.pdf",
    fileSize: "2.1 Mo",
    fileType: "pdf",
    isConfidential: false,
    signatories: ["Marie DUBOIS (Présidente)", "Claire MOREAU (Secrétaire)", "Jean-Pierre MARTIN (Trésorier)"],
    status: "valid",
    tags: ["AG Ordinaire", "PV", "Vote", "Quitus Trésorier", "Comptes"],
    season: "2024 - 2025",
    locationStored: "Registre Officiel des Délibérations - Folio 45-48",
    createdAt: "2026-01-15T14:00:00.000Z"
  },
  {
    id: "doc-4",
    title: "Procès-Verbal du Conseil d'Administration N°14",
    type: "Procès-Verbaux (PV d'AG & CA)",
    category: "Assemblées & Décisions",
    referenceNumber: "PV-CA-2026-02",
    issueDate: "2026-02-14",
    description: "Délibérations relatives aux investissements de mi-saison, achat de ballons neufs et préparation du tournoi printanier.",
    fileName: "PV_Conseil_Administration_Fevrier_2026.pdf",
    fileSize: "620 Ko",
    fileType: "pdf",
    isConfidential: false,
    signatories: ["Marie DUBOIS (Présidente)", "Claire MOREAU (Secrétaire)"],
    status: "valid",
    tags: ["CA", "PV", "Investissements", "Tournoi"],
    season: "2025 - 2026",
    locationStored: "Registre Officiel des Délibérations - Folio 49",
    createdAt: "2026-02-16T11:00:00.000Z"
  },
  {
    id: "doc-5",
    title: "Convention Municipale d'Occupation des Gymnases & Terrains",
    type: "Conventions & Partenariats",
    category: "Conventions & Partenariats",
    referenceNumber: "CONV-VILLE-2025-08",
    issueDate: "2025-08-25",
    validUntilDate: "2027-08-31",
    description: "Convention pluriannuelle avec la Direction de la Jeunesse et des Sports pour les créneaux d'entraînement du Gymnase Municipal et du Stade Principal.",
    fileName: "Convention_Mairie_Paris_Gymnases_2025_2027.pdf",
    fileSize: "3.4 Mo",
    fileType: "pdf",
    isConfidential: false,
    signatories: ["M. le Maire Adjoint aux Sports", "Marie DUBOIS (Présidente)"],
    status: "valid",
    tags: ["Convention", "Mairie", "Gymnase", "Créneaux", "Installations"],
    season: "2025 - 2026",
    locationStored: "Classeur Bleu - Conventions Publiques",
    createdAt: "2026-01-18T16:20:00.000Z",
    notes: "Renouvellement tacite prévu sous réserve d'envoi du bilan d'activité annuel."
  },
  {
    id: "doc-6",
    title: "Contrat de Partenariat & Sponsoring - Boulangerie Moderne",
    type: "Conventions & Partenariats",
    category: "Conventions & Partenariats",
    referenceNumber: "SPONSOR-2026-01",
    issueDate: "2026-01-05",
    validUntilDate: "2026-06-30",
    description: "Convention de sponsoring maillots de l'équipe Séniors Masculins (apport de 800€ + collations pour les matchs à domicile).",
    fileName: "Contrat_Partenariat_Boulangerie_Moderne_2026.pdf",
    fileSize: "1.1 Mo",
    fileType: "pdf",
    isConfidential: false,
    signatories: ["Gérant Boulangerie Moderne", "Jean-Pierre MARTIN (Trésorier)"],
    status: "valid",
    tags: ["Sponsoring", "Partenariat", "Maillot", "Finances"],
    season: "2025 - 2026",
    locationStored: "Classeur Sponsors & Mécénat - Dossier 3",
    createdAt: "2026-01-20T10:00:00.000Z"
  },
  {
    id: "doc-7",
    title: "Attestation Officielle d'Affiliation Fédérale (FFHB)",
    type: "Agréments & Affiliations",
    category: "Fédérations & Agréments",
    referenceNumber: "FFHB-AFFIL-5875042",
    issueDate: "2025-07-01",
    validUntilDate: "2026-08-31",
    description: "Certificat d'affiliation officielle auprès de la Fédération Française sous le n° de club 5875042 permettant l'engagement en compétitions officielles.",
    fileName: "Attestation_Affiliation_FFHB_2025_2026.pdf",
    fileSize: "490 Ko",
    fileType: "pdf",
    isConfidential: false,
    signatories: ["Secrétaire Général FFHB"],
    status: "valid",
    tags: ["Affiliation", "FFHB", "Fédération", "Compétition"],
    season: "2025 - 2026",
    locationStored: "Classeur Fédéral - Onglet 1",
    createdAt: "2026-01-22T08:45:00.000Z"
  },
  {
    id: "doc-8",
    title: "Arrêté d'Agrément Jeunesse et Sports",
    type: "Agréments & Affiliations",
    category: "Fédérations & Agréments",
    referenceNumber: "AGR-JS-75-2014-88",
    issueDate: "2014-11-20",
    description: "Agrément ministériel au titre du sport ouvrant droit aux subventions de l'Agence Nationale du Sport (ANS) et aux réductions SACEM.",
    fileName: "Arrete_Agrement_Ministeriel_Jeunesse_Sports.pdf",
    fileSize: "1.3 Mo",
    fileType: "pdf",
    isConfidential: false,
    signatories: ["Préfet de Région / DRAJES"],
    status: "valid",
    tags: ["Agrément", "Ministère", "ANS", "Subventions"],
    season: "Toutes saisons",
    locationStored: "Coffre-fort Bureau Direction - Dossier Agréments",
    createdAt: "2026-01-25T15:00:00.000Z"
  },
  {
    id: "doc-9",
    title: "Police d'Assurance Multirisque & Responsabilité Civile MAIF",
    type: "Assurances & Responsabilité Civile",
    category: "Assurances & Juridique",
    referenceNumber: "POLICE-MAIF-4820193-H",
    issueDate: "2026-01-01",
    validUntilDate: "2026-12-31",
    description: "Contrat d'assurance couvrant la responsabilité civile de l'association, la protection juridique, les dirigeants, bénévoles et adhérents.",
    fileName: "Attestation_Assurance_MAIF_RC_2026.pdf",
    fileSize: "2.4 Mo",
    fileType: "pdf",
    isConfidential: false,
    signatories: ["Agent Général MAIF", "Marie DUBOIS (Présidente)"],
    status: "valid",
    tags: ["Assurance", "MAIF", "Responsabilité Civile", "Sécurité"],
    season: "2025 - 2026",
    locationStored: "Classeur Assurances - Pochette Principale",
    createdAt: "2026-01-28T09:30:00.000Z"
  },
  {
    id: "doc-10",
    title: "Dossier CERFA 12156*06 - Demande de Subvention Municipale",
    type: "Dossiers Subventions & CERFA",
    category: "Finances & Subventions",
    referenceNumber: "SUBV-VILLE-2026-75",
    issueDate: "2026-01-10",
    validUntilDate: "2026-12-31",
    description: "Dossier officiel de demande de subvention au fonctionnement déposé auprès du Service des Sports de la Ville de Paris.",
    fileName: "Dossier_Subvention_CERFA_12156_Ville_Paris_2026.pdf",
    fileSize: "3.8 Mo",
    fileType: "pdf",
    isConfidential: false,
    signatories: ["Marie DUBOIS (Présidente)", "Jean-Pierre MARTIN (Trésorier)"],
    status: "valid",
    tags: ["Subvention", "CERFA", "Mairie", "Financement"],
    season: "2025 - 2026",
    locationStored: "Classeur Subventions - Chemise 2026",
    createdAt: "2026-01-30T14:15:00.000Z"
  },
  {
    id: "doc-11",
    title: "Bilan Financier & Compte de Résultat Officiel (2024-2025)",
    type: "Bilans & Comptes Financiers",
    category: "Finances & Subventions",
    referenceNumber: "COMPTES-2025-FINAL",
    issueDate: "2025-06-25",
    description: "Tableau de clôture des comptes financiers, charges, produits, état des amortissements et solde de trésorerie validé par le commissaire aux comptes.",
    fileName: "Bilan_Financier_Compte_Resultat_2024_2025.pdf",
    fileSize: "1.6 Mo",
    fileType: "pdf",
    isConfidential: false,
    signatories: ["Jean-Pierre MARTIN (Trésorier)", "Marie DUBOIS (Présidente)"],
    status: "valid",
    tags: ["Bilan", "Comptabilité", "Clôture", "Comptes"],
    season: "2024 - 2025",
    locationStored: "Bureau Trésorerie - Classeur Bilan",
    createdAt: "2026-02-01T17:00:00.000Z"
  },
  {
    id: "doc-12",
    title: "Convention de Mise à Disposition du Minibus Départemental",
    type: "Conventions & Partenariats",
    category: "Conventions & Partenariats",
    referenceNumber: "CONV-MINIBUS-2025",
    issueDate: "2025-09-15",
    validUntilDate: "2026-06-30",
    description: "Accord de prêt du minibus 9 places pour les déplacements des équipes en déplacement régional le week-end.",
    fileName: "Convention_Pret_Minibus_Comite_2025_2026.pdf",
    fileSize: "980 Ko",
    fileType: "pdf",
    isConfidential: false,
    signatories: ["Président du Comité Départemental", "Marie DUBOIS (Présidente)"],
    status: "valid",
    tags: ["Minibus", "Transport", "Déplacements", "Comité"],
    season: "2025 - 2026",
    locationStored: "Pochette Véhicule & Déplacements",
    createdAt: "2026-02-05T13:40:00.000Z"
  }
];

